USE teglon;
DELIMITER $$
CREATE FUNCTION `AngSep`(
    ra1 DOUBLE,
    dec1 DOUBLE,
    ra2 DOUBLE,
    dec2 DOUBLE
) RETURNS double
    DETERMINISTIC
BEGIN
    RETURN (DEGREES(ACOS(SIN(RADIANS(dec1))*SIN(RADIANS(dec2)) + COS(RADIANS(dec1))*COS(RADIANS(dec2))*COS(RADIANS(ra1- ra2)))));
END$$
DELIMITER ;