version: '2.4'
services:
    gw_api_prod:
        container_name: teglon_api_prod
        platform: linux/amd64
        build: .
        image: "davecoulter/teglon:0.0.1"
        mem_limit: ${MEM_LIMIT}
        cpus: ${CPU_LIMIT}
        command: gunicorn --bind 0.0.0.0:5000 web.manage:app --timeout 1200
        volumes:
            - ${VOL_APP}:/app
        ports:
          - 5000:5000
        links:
            - gw_db
        environment:
          FLASK_APP: web/project/__init__.py
          PYTHONPATH: /app
        depends_on:
          gw_db:
            condition: service_healthy
    gw_api_dev:
      container_name: teglon_api_debug
      platform: linux/amd64
      build: .
      image: "davecoulter/teglon:0.0.1"
      mem_limit: ${MEM_LIMIT}
      cpus: ${CPU_LIMIT}
      command: python /app/web/manage.py run -h 0.0.0.0
      volumes:
        - ${VOL_APP}:/app
      ports:
        - 5000:5000
      links:
        - gw_db
      environment:
        FLASK_APP: web/project/__init__.py
        FLASK_DEBUG: 1
        PYTHONPATH: /app
      depends_on:
        gw_db:
          condition: service_healthy
    gw_db:
        container_name: teglon_db
        image: "mysql:8.0.25"
        mem_limit: ${MEM_LIMIT}
        ports:
            - ${LOCAL_DB_PORT}:3306
        volumes:
            - ${VOL_DB}:/var/lib/mysql
            - ./db_init/db_configuration:/etc/mysql/conf.d
            - ./db_init/init.sql:/docker-entrypoint-initdb.d/1.sql
            - ./db_init/teglon_O4.sql:/docker-entrypoint-initdb.d/2.sql
            - ./db_init/angsep.sql:/docker-entrypoint-initdb.d/3.sql
            - ./db_init/backup_tables.sql:/docker-entrypoint-initdb.d/4.sql
            - ./db_init/delete_map.sql:/docker-entrypoint-initdb.d/5.sql
            - ./db_init/teglon_users.sql:/docker-entrypoint-initdb.d/6.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PWD}
        healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10
    gw_script:
      container_name: teglon_script
      platform: linux/amd64
      build:
        context: .
        args:
          DUSTMAPS_CONFIG_DIR: "./web/src/utilities"
      image: "davecoulter/teglon:0.0.2"

      mem_limit: ${MEM_LIMIT}
      cpus: ${CPU_LIMIT}
      volumes:
        - ${VOL_APP}:/app
      links:
        - gw_db
      environment:
        PYTHONPATH: /app
      depends_on:
        gw_db:
          condition: service_healthy
    gw_dev:
      container_name: teglon_dev
      platform: linux/amd64
      build: .
      image: "davecoulter/teglon:0.0.1"
      mem_limit: ${MEM_LIMIT}
      cpus: ${CPU_LIMIT}
      volumes:
        - ${VOL_APP}:/app
      environment:
        PYTHONPATH: /app
    nginx_prod:
      build:
          context: .
          dockerfile: Dockerfile.nginx
      volumes:
        - ${VOL_APP}:/app/
      ports:
        - 1337:80
      depends_on:
        - gw_api_prod
    nginx_dev:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      volumes:
        - ${VOL_APP}:/app/
      ports:
        - 1337:80
      depends_on:
        - gw_api_dev